version: "2"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: pillpool:latest # Naming the image (not using it)
    command: uwsgi --ini-paste development.ini
    volumes:
      - .:/app
    ports:
      - "6540:6540"
    environment:
      - PYRAMID_DEBUG_ROUTEMATCH=true